### ISSUE TITLE
Error: FilesService not initialized

### ISSUE THREAD

**Issue by RafaMalicia** [OpenVidu/openvidu-loadtest#27]
Hi, I'm an openvidu pro user trying to setup the client in KMS mode, however when I try to add a new subscriber I'm getting the below error, any clue?

https://x.x.x.x:5000/openvidu-browser/streamManager

`{
    "error": {
        "stack": "Error: FilesService not initialized\n    at Function.getInstance (/home/webadmin/openvidu-loadtest/browser-emulator/src/services/files.service.ts:8:19)\n    at new BrowserManagerService (/home/webadmin/openvidu-loadtest/browser-emulator/src/services/browser-manager.service.ts:22:53)\n    at Function.getInstance (/home/webadmin/openvidu-loadtest/browser-emulator/src/services/browser-manager.service.ts:30:37)\n    at /home/webadmin/openvidu-loadtest/browser-emulator/src/controllers/openvidu-browser.controller.ts:17:79\n    at Layer.handle [as handle_request] (/home/webadmin/openvidu-loadtest/browser-emulator/node_modules/express/lib/router/layer.js:95:5)\n    at next (/home/webadmin/openvidu-loadtest/browser-emulator/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/home/webadmin/openvidu-loadtest/browser-emulator/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/home/webadmin/openvidu-loadtest/browser-emulator/node_modules/express/lib/router/layer.js:95:5)\n    at /home/webadmin/openvidu-loadtest/browser-emulator/node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/home/webadmin/openvidu-loadtest/browser-emulator/node_modules/express/lib/router/index.js:335:12)",
        "message": "FilesService not initialized"
    }
}`

**Comment by ivchicano** [comment]
https://github.com/OpenVidu/openvidu-loadtest/commit/ff2b8ed9489e95bca73c47daadc0bcef339b8685 fixes this, please git pull and try again

**Comment by RafaMalicia** [comment]
It was fixed, thank you!
