### ISSUE TITLE
one to many load test

### ISSUE THREAD

**Issue by a7medo778** [OpenVidu/openvidu-loadtest#5]
hey guys,
i intend to use the app for a live video stream (one presenter through RTMP, 100k subscriber to view the stream via RTSP)

was a test like this done before? and if not how can i execute one
i am intersted if latency takes a hit

**Comment by micaelgallego** [comment]
WebRTC is not designed to have 100k viewers.

Some complex technology can be implemented to have those numbers with WebRTC. For example, https://millicast.com/ people has do it. 

But OpenVidu doesn't have the technology (transcoding, cascade media servers, simulcast...) to allow it. 

Nevertheless, it is in our roadmap.

**Comment by a7medo778** [comment]
hey @micaelgallego 
i just read the news about the scaling in the new version, does that mean that the single broadcast can be streamed through multiple media nodes increasing the number of subscribers infinitely ?

**Comment by micaelgallego** [comment]
Not now, but we are going to implement such technology in the near future.
